name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  debug:
    name: Build Debug
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'build_debug'
        skip-tracking: 'true'
      env:
        VERSION_CODE: ${{ github.run_id }}
        VERSION_SHA: ${{ github.sha }}