name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  debug:
    name: Build Debug
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'build_debug'
        skip-tracking: 'true'
      env:
        VERSION_CODE: ${{ github.run_id }}
        VERSION_SHA: ${{ github.sha }}

  release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - id: decode_keystore
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'android-signing-keystore.jks'
        encodedString: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
    - uses: actions/checkout@master
    - uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'build_release'
        skip-tracking: 'true'
      env:
        VERSION_CODE: ${{ github.run_id }}
        VERSION_SHA: ${{ github.sha }}
        SIGNING_KEYSTORE_PATH: ${{ steps.decode_keystore.outputs.filePath }}
        SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}