name: Release To Beta

on:
  push:
    branches:
    - beta

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
    - name: Retrieve Encryption Keys
      id: decode_keystore
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'android-signing-keystore.jks'
        encodedString: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
    - name: Checkout Source
      uses: actions/checkout@master
    - name: Bump app versionCode
      run: gawk -i inplace '/^[[:space:]]*versionCode[[:space:]]+[[:digit:]]+/ { $1 = "        "$1; $2 = $2 + 1; } 1' app/build.gradle
    - name: Read Version Code
      run: echo "VERSION_CODE=v$(gradle -q printVersionCode)" >> $GITHUB_ENV
    - name: Build APK
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'build_release'
        skip-tracking: 'true'
      env:
        VERSION_CODE: ${{ env.VERSION_CODE }}
        SIGNING_KEYSTORE_PATH: ${{ steps.decode_keystore.outputs.filePath }}
        SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.UPLOAD_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
    - name: Copy Release Notes
      run: cp ./fastlane/metadata/android/en-US/changelogs/CURRENT_VERSION.txt "./fastlane/metadata/android/en-US/changelogs/${{ env.VERSION_CODE }}.txt"
    - name: Upload release
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'publish_to_beta'
        skip-tracking: 'true'
        options: '{ "apk_path": "app/build/outputs/apk/release/app-release.apk" }'
      env:
        GOOGLE_PLAY_SERVICE_ACCOUNT_API_KEY_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_API_KEY_JSON }}
    - name: Commit Release Notes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Polaris Android CI
        author_email: antoine.gersant@lesforges.org
        message: 'Updated release notes and versionCode'
        add: '*.txt *.gradle'
        tag: 'google-play-beta --force'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
