name: Release To Production

on:
  push:
    tags:
    - 'production-release-candidate'

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@master
    - name: Read Version Name
      run: echo ::set-env name=VERSION_NAME::v$(gradle -q printVersionName)
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.1'
    - name: Upload release
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'promote_beta_to_production'
        skip-tracking: 'true'
      env:
        GOOGLE_PLAY_SERVICE_ACCOUNT_API_KEY_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_API_KEY_JSON }}
    - name: Update Production Git Tag
      uses: richardsimko/update-tag@master
      with:
        tag_name: production
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Add Version Git Tag
      uses: richardsimko/update-tag@master
      with:
        tag_name: ${{ env.VERSION_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
